# Generated by Django 3.2.15 on 2022-08-15 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=14, null=True)),
                ('endereco', models.CharField(max_length=60)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime(2022, 8, 15, 15, 24, 18, 342663))),
                ('faturamento_declarado', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosBancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=3)),
                ('agencia', models.CharField(max_length=6)),
                ('conta', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name='dadosbancarios',
            constraint=models.UniqueConstraint(fields=('banco', 'agencia', 'conta'), name='dados_bancarios_unique'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dados_bancarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.dadosbancarios'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('razao_social',), name='cliente_unique'),
        ),
    ]
